### ISSUE TITLE
Garbage collector unloads the music causing the game to crash

### ISSUE THREAD

**Issue by SomeUnusualGames** [lyte2d/lyte2d#24]
I'm having a strange crash when playing music, it plays fine for a while but at a certain moment it stops, the game continues working for a couple of seconds until it crashes with no error message.

When I only play the music file and don't do anything else there's no crash, so there's nothing wrong with the music file. I tried ogg and wav but it doesn't make a difference.

The music is [this one](https://opengameart.org/content/theme-of-the-masked-man-loopable-chiptune-slow-broody-adventure) (the full version). I'm on Windows using the latest desktop binary.

---

Looking at the `core_audio.c` file there doesn't seem to be anything strange, except for this:

https://github.com/lyte2d/lyte2d/blob/6a1900f8ce02b5fb6c756e1df8b56552fc4dbb0c/lyte_core/src/core_audio.c#L81-L86

Is there any particular reason the `Music` object is updated 4 times? All of my games that use raylib's audio module the music stream is updated only once and it works fine on desktop and the web, so why it's different here?
I'm not entirely sure whether or not this is the cause of the crash but it would be worth testing.

**Comment by SomeUnusualGames** [comment]
I _think_ I just found the cause of the crash. TL;DR: In my code, I only load the music and play it once at the beginning of the `app.lua` script. By not referencing it anywhere, the garbage collector acts on it and makes it unload when it shouldn't.

---

Enable `raudio` logging by commenting this line:
```c
#define RAUDIO_NOLOG // mg: no logging from raudio
```

I get this:
```
AUDIO: Device initialized successfully
    > Backend:       miniaudio / WASAPI
    > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
    > Channels:      2 -> 2    > Sample rate:   48000 -> 48000    > Periods size:  1440
```
after a while...
```
STREAM: Unloaded audio stream data from RAM
```
is lyte unloading the music object at the wrong time? Or maybe because there was a crash somewhere? How does lyte unload the music?

https://github.com/lyte2d/lyte2d/blob/6a1900f8ce02b5fb6c756e1df8b56552fc4dbb0c/lyte_api/src/api_generated.c#L1519-L1523

a-ha! could it be that the garbage collector is cleaning it up because in the `lyte.tick` function I never referenced the music object?

Let's try adding something simple that uses the music object, for example, let's draw on screen the length played:

```lua
local music = lyte.load_music("assets/music/theme-of-the-masked-man.ogg")
lyte.play_music(music)

function lyte.tick(df, width, height, resized, fullscreen)
  local played = lyte.get_music_length_played(music)
  -- ...couple of other things
  lyte.cls(0, 0, 0, 1)
  lyte.draw_text(tostring(played), 200, 200)
end
```

Now it doesn't crash! So my suspicion about the gc _could_ be right!

---

So, how do we fix this?

Should the unloading of the music rely solely on the gc? Would it be possible to keep the music object loaded (even if it's not being used) and unload it **only** when the app is quitting?

The easiest workaround is simply add any function that does something with the music, but as I said that's a workaround, not a real solution.

I noticed this for the canvas and font objects:

```c
    // save this value to registry to prevent it from being GC'd
    lua_pushvalue(L, -1); // duplicate the object
    lua_setfield(L, LUA_REGISTRYINDEX, "lyte_canvas_image_SAVE");
```

I added the same thing at the `api_load_music` function and it works, but I'm not familiar with lua C api so this may cause issues somewhere else.

**Comment by morew4rd** [comment]
Great find!  Yeah, your analysis is spot on, this is a GC issue.  

And you're also right that we should keep a reference to the `Music`. This should be done on the `play_music` API, however, not `load_music`. Latter could be an issue with multiple music objects.  The idea is to always have a reference to the currently used resource object (`Canvas`, `Font` and clearly `Music` too.)

I'll fix this when I get access to my dev machine, in the meantime your workaround or custom build should work as a workaround. (I'd just move the registry saving code to `play_music` instead.)

Here's the plan for the "official" fix:

Since the API code surface is generated for metadata, we need to set the `save_to_registry` flag to `true` for `play_music`, similar to `set_canvas` and regenerate the API code (with `gen.sh`: https://github.com/lyte2d/lyte2d/blob/main/lyte_api/gen.sh). 

`set_canvas` 
https://github.com/lyte2d/lyte2d/blob/main/lyte_api/defs/defs_lyte.lua#L152

`play_music`
https://github.com/lyte2d/lyte2d/blob/main/lyte_api/defs/defs_lyte.lua#L390

Also will need to copy the generated code to the correct location. This wasn't automated, IIRC.

**Comment by morew4rd** [comment]
Also, re multiple `UpdateMusicStream` calls on raylib's auido module: I was having some issues on the WASM build with some music files. They either never started (only sometimes) or failed to loop (also sometimes.)  This was a workaround.  I didn't investigate furtner. I wish I remembered which files those were...
