### ISSUE TITLE
API to enable text entry

### ISSUE THREAD

**Issue by morew4rd** [lyte2d/lyte2d#44]
Lyte2D's current "keyboard input" API (`is_key_(down/pressed/released/repeat)`) is great for games, but it makes it very hard to implement text entry (think filling fields, or even text editors)

A possible way to solve this would be exposing corresponding tables with an API like `get_(down/pressed/released/repeat)_keys`.

Another would be following LOVE2D (in spirit, as Lyte2D does not favor events): `start_textinput`, `stop_textinput`, `get_textinput_string`, `reset_textinput_string`.

Related: #4

**Comment by Zorbn** [comment]
I think this API should be implemented using `glfwSetCharCallback` since that's probably the easiest way to make text input work with different layouts + capitals/lowercase + non-ascii text. In that case I would prefer the second API with `start_textinput`, etc.

In my past projects I've written/used API's like the first one that give you a list of pressed keys, but it felt kind of clunky to implement text input that way.

https://www.glfw.org/docs/latest/input_guide.html#input_char

**Comment by morew4rd** [comment]
Ah, I think we may need both. 

(The former to make key configuration UIs easy. Should probably file another issue for that.)

**Comment by morew4rd** [comment]
Initial investigation: we may need a simple utf8 library with this...

**Comment by morew4rd** [comment]
Basic API sample:

```
local text = ""

function lyte.tick()
    lyte.cls(0,0,0,0)
    lyte.draw_text("input: " .. text, 0, 0)

    text = text .. lyte.get_textinput()

    if lyte.is_key_pressed("backspace") or lyte.is_key_repeat("backspace") then

        text = text:sub(0, #text-1)
    end
    if lyte.is_key_pressed("enter") then
        print(text)
        text = ""
    end
end
```

Open: system clipboard access

**Comment by morew4rd** [comment]
Promising utf8 library to complete this issue: https://github.com/starwing/luautf8

Looks like it's time tested, and already supports lua5.3 utf8 API surface.

Will investigate further

**Comment by morew4rd** [comment]
This is finished in https://github.com/lyte2d/lyte2d/commit/6d10e809ec0f35c759c66c67ba9f33941aee2f98.

The additional work to get the list of pressed keys is tracked here: https://github.com/lyte2d/lyte2d/issues/50
